const { Pets } = require('../models');

const petData = [
    {
        breed_id: 1,
        category_id: 1,
        pet_name: "Duke",
        Size:"Large",
        Sex:"Male",
        Age:"2",
        Description:"My name is Duke-I am a big, affectionate goofball who loves to work my brain doing loads of enrichment puzzles (especially if there is food involved!).Good for families and will n need a Backyard to run around in but loves to sleep inside",
        Cost:300,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/golden.jfif',
        Location: "Newcastle, NSW",
        isAdopted: true,
        // Adopted_by: "",

    },
    {
        breed_id: 2,
        category_id: 1,
        pet_name: "Molly",
        Size:"Small",
        Sex:"Female",
        Age:"4",
        Description:"Molly is looking for a new family! Sweet, affectionate and loves to snuggle up. She is an indoor dog and would need someone who will be home during the day.",
        Cost:400,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/Bulldog_Featured-Image.jpg',
        Location: "Sydney, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },

    {
        breed_id: 5,
        category_id: 2,
        pet_name: "Blinky",
        Size:"Small",
        Sex:"Female",
        Age:"2",
        Description:"I am beautiful, dainty, full of character, and looking for my furrever home, I'm very vocal and enjoy having a good chat.I'm currently living with my foster parent, and she reports to the team that I am cute, and enjoy playing with my string toy.",
        Cost:200,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/siemesecat.jpg',
        Location: "Newtown, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 12,
        category_id: 1,
        pet_name: "Buffy",
        Size:"Small",
        Sex:"Female",
        Age:"2",
        Description:"Hi I'm Buffy. I've been living in foster care for a little while now as the shelter was a bit too overwhelming, but I'm so excited to be finding my forever home! I'm a very sweet girl, looking for a home where I can be indoors and out.",
        Cost:350,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/malltese.jpeg',
        Location: "Camden, NSW",
        isAdopted: true,
        // Adopted_by: "",

    },
    {
        breed_id: 4,
        category_id: 1,
        pet_name: "Tessa",
        Size:"Medium",
        Sex:"Female",
        Age:"5",
        Description:"Woof! My name is Tessa, nice to meet you. I'm a Staffy on the lookout for a loving forever home. Being an American Staffy, I'm really your typical Staffy that loves getting all the attention in the world and being a sook.",
        Cost:300,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/staffy2.jpg',
        Location: "Hornsby, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 15,
        category_id: 2,
        pet_name: "Casper",
        Size:"Small",
        Sex:"Male",
        Age:"2",
        Description:"Hey everybody!!! I am a friendly and happy kitty waiting for my forever home! Could this be with you? I am playful, confident, and most of all super cute! I am looking for a place to call home that I can live out my days!",
        Cost:100,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/catcasper.jpg',
        Location: "Newcastle, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 13,
        category_id: 1,
        pet_name: "Rusty",
        Size:"Large",
        Sex:"Male",
        Age:"1",
        Description:"Meet Rusty! I'm on the lookout for my brand new forever home and I'm hoping it could be with you! The staff here adore me and I adore them back but its time for me to settle down somewhere permanent.",
        Cost:300,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/german%20shep.jpg',
        Location: "Bankstown, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 1,
        category_id: 1,
        pet_name: "Frankie",
        Size:"Large",
        Sex:"Male",
        Age:"1",
        Description:"Meet Frankie! Being a pup, he will be easily trainable and these loyal dogs love to please their owners. He still has so much to learn about the world and life and would love to be in a home where he is included as a member of the family. ",
        Cost:400,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/golden-retriever_Shutterstock.jpg',
        Location: "Sydney, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 15,
        category_id: 2,
        pet_name: "Luna",
        Size:"Small",
        Sex:"Female",
        Age:"5",
        Description:"Hi all! My name is Luna and I am ready to find my forever home. I came into the shelter through no fault of my own and it took a while for me to adjust properly to the shelter life.",
        Cost:150,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/cat%20luna.jpg',
        Location: "Castle Hill, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 3,
        category_id: 1,
        pet_name: "Max",
        Size:"Large",
        Sex:"Male",
        Age:"2",
        Description:"Hi guys my name is Max! I am higher energy at the moment as I am a young boy and will need daily opportunities to explore and learn. I only have some basic manners so an owner that is committed to my ongoing training is in my best interest",
        Cost:400,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/Border_Collie_Lying_Down_On_Grass.jpg',
        Location: "Sydney, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 1,
        category_id: 1,
        pet_name: "Milo",
        Size:"Large",
        Sex:"Male",
        Age:"2",
        Description:"Hi I'm Milo. I'm a medium energy dog, I really like to play and explore and a couple of rounds of fetch in the yard will make me a happy camper!",
        Cost:350,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/pug.jpg',
        Location: "Gosford, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 14,
        category_id: 1,
        pet_name: "Millie",
        Size:"Small",
        Sex:"Female",
        Age:"2",
        Description:"Millie is a high energy pup who loves to play, go on walks, and explore the world. She is inquisitive and loves to learn new things. She is a very loyal girl and will love to spend time with her new family.",
        Cost:500,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/cavoodlecute.jpg',
        Location: "Redfern, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 8,
        category_id: 3,
        pet_name: "Jilly",
        Size:"Small",
        Sex:"Female",
        Age:"1",
        Description:"Hi I'm Jilly. I'm an active entertaining little bird with a HUGE attitude, and I have a lot to say! I enjoy having toys and things to play with and tear apart, and a space to stretch my wings!",
        Cost:100,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/canary2.jpg',
        Location: "Sydney, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 10,
        category_id: 3,
        pet_name: "Buddy",
        Size:"Small",
        Sex:"Male",
        Age:"2",
        Description:"I'm a talkative active little bird with a HUGE attitude! I enjoy having toys and things to play with and tear apart, space to stretch my wings and of course some people to yell at when I want to!",
        Cost:50,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/buddy.jpg',
        Location: "Sutherland, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 4,
        category_id: 1,
        pet_name: "Zeus",
        Size:"Small",
        Sex:"Male",
        Age:"1",
        Description:"I'm Beau and I'm ready to go! I am an energetic, friendly, bouncy young man who sometimes gets a little too excited when greeting people",
        Cost:200,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/staffy%20pup.jpg',
        Location: "Maitland, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 16,
        category_id: 1,    
        pet_name: "Lucy",
        Size:"Large",
        Sex:"Female",
        Age:"4",
        Description:"I'm a sweet relaxed girl with a gentle and nurturing soul. Ideal for a family with older children, I'd be the perfect companion for a family who wants a quiet, friendly pet with good house manners",
        Cost:300,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/greyhound2.jpg',
        Location: "Westmead, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
    {
        breed_id: 15,
        category_id: 2,
        pet_name: "Jazz",
        Size:"Small",
        Sex:"Female",
        Age:"1",
        Description:"Jazz is a bundle of energy, curiosity, and love. She loves to explore her surroundings, play with her toys, and spend time cuddling with her owners.",
        Cost:150,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/cat%20jazz.jpg',
        Location: "Newtown, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },

    {
        breed_id: 5,
        category_id: 2,
        pet_name: "Ivy",
        Size:"Small",
        Sex:"Female",
        Age:"2",
        Description:"Meet Ivy, a sweet and loving female cat that is looking for her forever home! This affectionate kitty loves snuggling up with her family and getting plenty of pets and cuddles. Ivy is a beautiful tabby with white markings.",
        Cost:100,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/cativy.jpg',
        Location: "Marrickville, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },

    {
        breed_id: 5,
        category_id: 2,
        pet_name: "Simmo",
        Size:"Small",
        Sex:"Male",
        Age:"4",
        Description:"Simmo is desperately looking forward to finding his forever home, life in a cage just doesn't suit him at all. Simmo adoption fee is $50.00 and includes his desexing and lifetime registration.",
        Cost:200,
        Picture:'https://bootcampsmullock.blob.core.windows.net/pets/catsimmo.jpg',
        Location: "Newtown, NSW",
        isAdopted: false,
        // Adopted_by: "",

    },
   
];

const seedPets = () => Pets.bulkCreate(petData);

module.exports = seedPets;